packages:
    - "packages/*"
    - "examples/*"

allowBuilds:
    "@parcel/watcher": false
    "@vscode/vsce-sign": false
    bcrypt: true
    esbuild: false
    keytar: false
    sharp: false

peerDependencyRules:
    ignoreMissing:
        - "@emnapi/core"
        - "@emnapi/runtime"
