//#region -------------------------------------------------- Type Imports

import type {
	AstroComponentsMap,
	CSSMarkupMap,
	JSON_AstroComponent,
	JSON_CSSMarkup,
	JSON_Lists
} from "../_shared/types.js"
import type { ConfigSchema, CustomElementsMap, JSON_CustomElement } from "../_shared/validation.js"

//#endregion ----------------------------------------------- Type Imports

//#region -------------------------------------------------- Module Imports

import path from "node:path"
import { GLOBALS } from "../../globals.js"
import { createAstroComponentsMap } from "../_shared/astro.js"
import { loadJSONFile } from "../_shared/fs.js"

//#endregion ----------------------------------------------- Module Imports

type RT_getGeneratedData = {
	customElementsMap: CustomElementsMap
	astroComponentsMap: AstroComponentsMap
	cssMarkupMap: CSSMarkupMap
	listContent: JSON_Lists
	projectDir: string
	cssDir: string
}

/*******************************************************************************
 *
 * Function that gets all the data generated by the `gen` CLI commmand..
 *
 ******************************************************************************/

export function getGeneratedData(currentDir: string): RT_getGeneratedData {
	const { outDir, projectDir, cssDir } = _loadConfig()

	const { customElementsContent, nativeElementsContent, astroComponentsContent, listContent, cssMarkupJSON } =
		_loadJSONContent()

	return {
		customElementsMap: _createCustomElementsMap(),
		astroComponentsMap: createAstroComponentsMap(astroComponentsContent),
		cssMarkupMap: _createCssMarkupMap(),
		listContent,
		projectDir,
		cssDir
	}

	//* ---------- Helpers -----------------------------------------------

	type RT__loadConfig = {
		projectDir: string
		outDir: string
		cssDir: string
	}

	function _loadConfig(): RT__loadConfig {
		const configContent = loadJSONFile(`${currentDir}/${GLOBALS.HAQ_CONFIG_JSON_FILE_NAME}`) as ConfigSchema

		return {
			projectDir: path.join(currentDir, configContent.projectDir),
			outDir: path.join(currentDir, configContent.outDir),
			cssDir: path.join(currentDir, configContent.globalCssDir)
		}
	}

	type RT__loadJSONContent = {
		listContent: JSON_Lists
		astroComponentsContent: JSON_AstroComponent[]
		customElementsContent: JSON_CustomElement[]
		nativeElementsContent: JSON_CustomElement[]
		cssMarkupJSON: JSON_CSSMarkup[]
	}
	function _loadJSONContent(): RT__loadJSONContent {
		const genOutputDir = `${outDir}/${GLOBALS.GENERATED_TYPES_FOLDER}`

		return {
			listContent: loadJSONFile(`${genOutputDir}/${GLOBALS.GEN_LISTS_JSON_FILE_NAME}`) as JSON_Lists,
			astroComponentsContent: loadJSONFile(
				`${genOutputDir}/${GLOBALS.GEN_ASTRO_COMPONENTS_JSON_FILE_NAME}`
			) as JSON_AstroComponent[],
			customElementsContent: loadJSONFile(
				`${genOutputDir}/${GLOBALS.GEN_CUSTOM_ELEMENTS_JSON_FILE_NAME}`
			) as JSON_CustomElement[],
			nativeElementsContent: loadJSONFile(
				`${genOutputDir}/${GLOBALS.NATIVE_ELEMENTS_JSON_FILE_NAME}`
			) as JSON_CustomElement[],
			cssMarkupJSON: loadJSONFile(`${genOutputDir}/${GLOBALS.GEN_CSS_JSON_FILE_NAME}`) as JSON_CSSMarkup[]
		}
	}

	function _createCssMarkupMap(): CSSMarkupMap {
		const cssMarkupMap: CSSMarkupMap = new Map()
		for (const record of cssMarkupJSON) {
			cssMarkupMap.set(record.cssFilePath, {
				componentName: record.componentName,
				astroFilePath: record.astroFilePath,
				cssFilePath: record.cssFilePath,
				flatMarkup: record.flatMarkup
			})
		}

		return cssMarkupMap
	}

	function _createCustomElementsMap(): CustomElementsMap {
		const customElementsMap: CustomElementsMap = new Map()
		for (const record of customElementsContent) {
			customElementsMap.set(record.tag, {
				attrs: record.attrs,
				cssDynamicVars: record.cssDynamicVars,
				cssStaticVars: record.cssStaticVars
			})
		}
		for (const record of nativeElementsContent) {
			const extendedNativeEl = customElementsMap.get(record.tag)
			customElementsMap.set(record.tag, {
				attrs:
					extendedNativeEl && record.attrs && extendedNativeEl.attrs
						? [...record.attrs, ...extendedNativeEl.attrs]
						: record.attrs,
				cssDynamicVars: record.cssDynamicVars,
				cssStaticVars: record.cssStaticVars
			})
		}

		return customElementsMap
	}
}
