//! Do not edit this file! It will be overwritten! -----------------------------------------------

export type {}

declare global {
	namespace HAQ {
		interface AppComponentMap {
			MyForm: typeof import("./../app-components/MyForm/MyForm.js").MyForm
			MyHeader: typeof import("./../app-components/MyHeader/MyHeader.js").MyHeader
			PerfectNumber: typeof import("./../app-components/PerfectNumber/PerfectNumber.js").PerfectNumber
		}
	}
}
