//! Do not edit this file! It will be overwritten! -----------------------------------------------

export type {}

declare global {
	namespace astroHTML.JSX {
		//* ---------- Custom Generated Attributes -----------------------------------------------

		interface HAQ_GlobalAttributes {
			d_lang?: "ar" | undefined
		}

		/* svg-icon */

		interface SvgIconAttributes extends HTMLAttributes {
			d_icon: "html" | "css" | "plus" | "minus"
		}

		/* a */

		interface AnchorHTMLAttributes {
			d_active?: boolean | undefined
		}

		/* my-confetti */

		interface MyConfettiAttributes extends HTMLAttributes {
			d_particle_count: `${number}`
			d_animate?: boolean | undefined
		}

		/* my-confetti-particle */

		interface MyConfettiParticleAttributes extends HTMLAttributes {}

		/* my-counter */

		interface MyCounterAttributes extends HTMLAttributes {}

		/* odd-even */

		interface OddEvenAttributes extends HTMLAttributes {}

		/* Custom Intrinsic Elements
        -----------------------------------------------*/

		interface DefinedIntrinsicElements {
			"svg-icon": SvgIconAttributes
			"my-confetti": MyConfettiAttributes
			"my-confetti-particle": MyConfettiParticleAttributes
			"my-counter": MyCounterAttributes
			"odd-even": OddEvenAttributes
		}
	}
}
