//! Do not edit this file! It will be overwritten! -----------------------------------------------

export type {}

declare global {
	namespace HAQ {
		interface CustomElementCustomProperties {
			"my-confetti-particle": "--__bkgColor" | "--__left" | "--__delay" | "--__duration"

			html: "--__vh"
		}
	}
}
