//! Do not edit this file! It will be overwritten! -----------------------------------------------

//@ts-nocheck

import type {
	HAQ_AppComponentByName,
	HAQ_AttributesByTag,
	HAQ_CustomEventsByTag,
	HAQ_DOMElement,
	HAQ_HTMLFormElement,
	HAQ_HTMLTagTypes,
	HAQ_MarkupAlias,
	HAQ_MatchingSelectorsByTag,
	HAQ_StylePropertiesByTag
} from "@haq/astro/types"

// LINK src/app-components/MyForm/MyForm.astro

export type MU_MyForm = {
	HAQ_tag: "form"
	HAQ_elType: HAQ_HTMLFormElement
	HAQ_attributes: HAQ_AttributesByTag<"form">
	HAQ_matchingSelectors: HAQ_MatchingSelectorsByTag<"form">
	HAQ_styleProperties: HAQ_StylePropertiesByTag<"form">
	HAQ_id: "myForm"
	HAQ_selector: "#myForm"
	HAQ_formData: FD_MyForm
}

// LINK src/app-components/MyHeader/MyHeader.astro

export type MU_MyHeader = {
	HAQ_tag: "header"
	HAQ_elType: HAQ_HTMLTagTypes["header"]
	HAQ_attributes: HAQ_AttributesByTag<"header">
	HAQ_matchingSelectors: HAQ_MatchingSelectorsByTag<"header">
	HAQ_styleProperties: HAQ_StylePropertiesByTag<"header">
	HAQ_id: "header"
	HAQ_selector: "#header"
	HAQ_children: {
		MyConfetti: HAQ_MarkupAlias<MU_MyConfetti>
		Nav: {
			HAQ_tag: "nav"
			HAQ_elType: HAQ_HTMLTagTypes["nav"]
			HAQ_attributes: HAQ_AttributesByTag<"nav">
			HAQ_matchingSelectors: HAQ_MatchingSelectorsByTag<"nav">
			HAQ_styleProperties: HAQ_StylePropertiesByTag<"nav">
			HAQ_selector: "[x_sel='nav']"
			HAQ_children: { NavLink: HAQ_MarkupAlias<MU_NavLink> }
		}
	}
}

// LINK src/app-components/PerfectNumber/PerfectNumber.astro

export type MU_PerfectNumber = {
	HAQ_tag: "div"
	HAQ_elType: HAQ_HTMLTagTypes["div"]
	HAQ_attributes: HAQ_AttributesByTag<"div">
	HAQ_matchingSelectors: HAQ_MatchingSelectorsByTag<"div">
	HAQ_styleProperties: HAQ_StylePropertiesByTag<"div">
	HAQ_id: "perfectNumber"
	HAQ_selector: "#perfectNumber"
	HAQ_children: {
		ResultHeading: {
			HAQ_tag: "h1"
			HAQ_elType: HAQ_HTMLTagTypes["h1"]
			HAQ_attributes: HAQ_AttributesByTag<"h1">
			HAQ_matchingSelectors: HAQ_MatchingSelectorsByTag<"h1">
			HAQ_styleProperties: HAQ_StylePropertiesByTag<"h1">
			HAQ_selector: "[x_sel='result-heading']"
			HAQ_classList: "clr-accent"
		}
		OddEven: HAQ_MarkupAlias<MU_OddEven>
	}
}

// LINK src/components/NavLink.astro

export type MU_NavLink = {
	HAQ_tag: "a"
	HAQ_elType: HAQ_HTMLTagTypes["a"]
	HAQ_attributes: HAQ_AttributesByTag<"a">
	HAQ_matchingSelectors: HAQ_MatchingSelectorsByTag<"a">
	HAQ_styleProperties: HAQ_StylePropertiesByTag<"a">
	HAQ_selector: "[x_sel='nav-link']"
	HAQ_eventListenerType: "click"
}

// LINK src/components/OldMyHeader.astro

export type MU_OldMyHeader = {
	HAQ_tag: "header"
	HAQ_elType: HAQ_HTMLTagTypes["header"]
	HAQ_attributes: HAQ_AttributesByTag<"header">
	HAQ_matchingSelectors: HAQ_MatchingSelectorsByTag<"header">
	HAQ_styleProperties: HAQ_StylePropertiesByTag<"header">
	HAQ_selector: "[x_sel='header']"
	HAQ_children: {
		Nav: {
			HAQ_tag: "nav"
			HAQ_elType: HAQ_HTMLTagTypes["nav"]
			HAQ_attributes: HAQ_AttributesByTag<"nav">
			HAQ_matchingSelectors: HAQ_MatchingSelectorsByTag<"nav">
			HAQ_styleProperties: HAQ_StylePropertiesByTag<"nav">
			HAQ_selector: "[x_sel='nav']"
		}
	}
}

// LINK src/components/SvgIcon/SvgIcon.astro

export type MU_SvgIcon = {
	HAQ_tag: "svg-icon"
	HAQ_elType: HAQ_HTMLTagTypes["svg-icon"]
	HAQ_attributes: HAQ_AttributesByTag<"svg-icon">
	HAQ_matchingSelectors: HAQ_MatchingSelectorsByTag<"svg-icon">
	HAQ_styleProperties: HAQ_StylePropertiesByTag<"svg-icon">
	HAQ_selector: unknown
}

// LINK src/components/btns/MinusBtn.astro

export type MU_MinusBtn = {
	HAQ_tag: "button"
	HAQ_elType: HAQ_HTMLTagTypes["button"]
	HAQ_attributes: HAQ_AttributesByTag<"button">
	HAQ_matchingSelectors: HAQ_MatchingSelectorsByTag<"button">
	HAQ_styleProperties: HAQ_StylePropertiesByTag<"button">
	HAQ_selector: "[x_sel='minus-btn']"
	HAQ_eventListenerType: "click"
	HAQ_children: { SvgIcon: HAQ_MarkupAlias<MU_SvgIcon> }
}

// LINK src/components/btns/PlusBtn.astro

export type MU_PlusBtn = {
	HAQ_tag: "button"
	HAQ_elType: HAQ_HTMLTagTypes["button"]
	HAQ_attributes: HAQ_AttributesByTag<"button">
	HAQ_matchingSelectors: HAQ_MatchingSelectorsByTag<"button">
	HAQ_styleProperties: HAQ_StylePropertiesByTag<"button">
	HAQ_selector: "[x_sel='plus-btn']"
	HAQ_eventListenerType: "click"
	HAQ_children: { SvgIcon: HAQ_MarkupAlias<MU_SvgIcon> }
}

// LINK src/layouts/Scaffold.astro

export type MU_Scaffold = {
	HAQ_tag: "html"
	HAQ_elType: HAQ_HTMLTagTypes["html"]
	HAQ_attributes: HAQ_AttributesByTag<"html">
	HAQ_matchingSelectors: HAQ_MatchingSelectorsByTag<"html">
	HAQ_styleProperties: HAQ_StylePropertiesByTag<"html">
	HAQ_selector: unknown
	HAQ_children: { MyHeader: HAQ_MarkupAlias<MU_MyHeader> }
}

// LINK src/web-components/MyConfetti/MyConfetti.astro

export type MU_MyConfetti = {
	HAQ_tag: "my-confetti"
	HAQ_elType: HAQ_HTMLTagTypes["my-confetti"]
	HAQ_attributes: HAQ_AttributesByTag<"my-confetti">
	HAQ_matchingSelectors: HAQ_MatchingSelectorsByTag<"my-confetti">
	HAQ_styleProperties: HAQ_StylePropertiesByTag<"my-confetti">
	HAQ_selector: "my-confetti"
	HAQ_isWebComponent: true
	HAQ_children: { MyConfettiParticle: HAQ_MarkupAlias<MU_MyConfettiParticle> & { HAQ_isMaybeRendered: true } }
}

// LINK src/web-components/MyConfetti/MyConfettiParticle.astro

export type MU_MyConfettiParticle = {
	HAQ_tag: "my-confetti-particle"
	HAQ_elType: HAQ_HTMLTagTypes["my-confetti-particle"]
	HAQ_attributes: HAQ_AttributesByTag<"my-confetti-particle">
	HAQ_matchingSelectors: HAQ_MatchingSelectorsByTag<"my-confetti-particle">
	HAQ_styleProperties: HAQ_StylePropertiesByTag<"my-confetti-particle">
	HAQ_selector: "my-confetti-particle"
}

// LINK src/web-components/MyCounter/MyCounter.astro

export type MU_MyCounter = {
	HAQ_tag: "my-counter"
	HAQ_elType: HAQ_HTMLTagTypes["my-counter"]
	HAQ_attributes: HAQ_AttributesByTag<"my-counter">
	HAQ_matchingSelectors: HAQ_MatchingSelectorsByTag<"my-counter">
	HAQ_styleProperties: HAQ_StylePropertiesByTag<"my-counter">
	HAQ_selector: "my-counter"
	HAQ_isWebComponent: true
	HAQ_children: {
		MinusBtn: HAQ_MarkupAlias<MU_MinusBtn>
		Count: {
			HAQ_tag: "span"
			HAQ_elType: HAQ_HTMLTagTypes["span"]
			HAQ_attributes: HAQ_AttributesByTag<"span">
			HAQ_matchingSelectors: HAQ_MatchingSelectorsByTag<"span">
			HAQ_styleProperties: HAQ_StylePropertiesByTag<"span">
			HAQ_selector: "[x_sel='count']"
		}
		PlusBtn: HAQ_MarkupAlias<MU_PlusBtn>
	}
}

// LINK src/web-components/OddEven/OddEven.astro

export type MU_OddEven = {
	HAQ_tag: "odd-even"
	HAQ_elType: HAQ_HTMLTagTypes["odd-even"]
	HAQ_attributes: HAQ_AttributesByTag<"odd-even">
	HAQ_matchingSelectors: HAQ_MatchingSelectorsByTag<"odd-even">
	HAQ_styleProperties: HAQ_StylePropertiesByTag<"odd-even">
	HAQ_selector: "odd-even"
	HAQ_isWebComponent: true
	HAQ_children: {
		Result: {
			HAQ_tag: "h2"
			HAQ_elType: HAQ_HTMLTagTypes["h2"]
			HAQ_attributes: HAQ_AttributesByTag<"h2">
			HAQ_matchingSelectors: HAQ_MatchingSelectorsByTag<"h2">
			HAQ_styleProperties: HAQ_StylePropertiesByTag<"h2">
			HAQ_selector: "[x_sel='result']"
		}
		MyCounter: HAQ_MarkupAlias<MU_MyCounter>
	}
}

// LINK src/app-components/MyForm/MyForm.astro

export type FD_MyForm = {
	fullName: string
	email: string
	password: string
	role: "ADMIN" | "CLIENT"
	profilePic: File
}

export type HAQ_AppComponents_1 = {
	// LINK src/pages/index.astro

	"/": { MyHeader: HAQ_AppComponentByName<"MyHeader"> }

	// LINK src/pages/tutorial/app-components.astro

	"/tutorial/app-components": {
		MyHeader: HAQ_AppComponentByName<"MyHeader">
		PerfectNumber: HAQ_AppComponentByName<"PerfectNumber">
	}

	// LINK src/pages/tutorial/custom-elements.astro

	"/tutorial/custom-elements": { MyHeader: HAQ_AppComponentByName<"MyHeader"> }

	// LINK src/pages/tutorial/custom-events.astro

	"/tutorial/custom-events": { MyHeader: HAQ_AppComponentByName<"MyHeader"> }

	// LINK src/pages/tutorial/web-components.astro

	"/tutorial/web-components": { MyHeader: HAQ_AppComponentByName<"MyHeader"> }
}
