//! Do not edit this file! It will be overwritten! -----------------------------------------------

// LINK src/pages/index.astro

export type HAQ_PageRoute =
	| "/"
	| "/tutorial/app-components"
	| "/tutorial/custom-elements"
	| "/tutorial/custom-events"
	| "/tutorial/web-components"

export type HAQ_PartialRoute = never

export type HAQ_EmailRoute = never

export type HAQ_RenderedRoute = HAQ_PageRoute | HAQ_PartialRoute | HAQ_EmailRoute
