//! Do not edit this file! It will be overwritten! -----------------------------------------------

export type {}

declare global {
	namespace HAQ {
		interface WebComponentTagNameMap {
			"my-confetti": {
				el: import("./../web-components/MyConfetti/MyConfetti.js").MyConfetti
				customEvents: typeof import("./../web-components/MyConfetti/MyConfetti.js").MyConfetti.__T_customEvents
			}
			"my-counter": {
				el: import("./../web-components/MyCounter/MyCounter.js").MyCounter
				customEvents: typeof import("./../web-components/MyCounter/MyCounter.js").MyCounter.__T_customEvents
			}
			"odd-even": {
				el: import("./../web-components/OddEven/OddEven.js").OddEven
				customEvents: typeof import("./../web-components/OddEven/OddEven.js").OddEven.__T_customEvents
			}
		}
	}
}
