//#region -------------------------------------------------- Module Imports

import { jsonrepair } from "jsonrepair"
import { GLOBALS } from "../../globals.js"
import { HAQError } from "./errors.js"

//#endregion ----------------------------------------------- Module Imports

export function formatDate(d?: Date): string {
	const date = d ? new Date(d) : new Date() //get GMT timezone
	const year = date.getFullYear()
	const month = date.getMonth()
	const day = date.getDate()
	const hours = date.getHours()
	let minutes: string | number = date.getMinutes()
	minutes = minutes < 10 ? `0${minutes}` : minutes
	const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
	return `${months[month]} ${day}, ${year} at ${hours}:${minutes}`
}

export function removeEmptyLines(str: string): string {
	return str.replace(/^\s*\n/gm, "")
}

export function removeTrailingSlash(str: string): string {
	return str.replace(GLOBALS.REGEX_TRAILING_SLASH, "")
}

export function kebab2Pascal(str: string): string {
	const strAtrr = str.split("-")
	for (let i = 0; i < strAtrr.length; i++) {
		const currentChar = strAtrr[i]
		if (!currentChar) continue
		strAtrr[i] = currentChar.slice(0, 1).toUpperCase() + currentChar.slice(1, currentChar.length)
	}
	return strAtrr.join("")
}

export function pascal2Kebab(str: string): string {
	return str.replace(/([a-z0–9])([A-Z])/g, "$1-$2").toLowerCase()
}

export function addDisclaimerComment(): string {
	return "//! Do not edit this file! It will be overwritten! -----------------------------------------------\n\n"
}

export function injectTypesInGlobalNamespace(types: string, localTypes?: string): string {
	return ` export type {}\n\n ${localTypes ? localTypes : ""} declare global {${types}}`
}
export function containsUppercase(str: string): boolean {
	return GLOBALS.REGEX_UPPER_CASE.test(str)
}

export function getDuplicateArrayItem(array: string[]): string | null {
	const valuesSoFar = Object.create(null)
	for (const item of array) {
		const value = item
		if (!value) continue
		if (value in valuesSoFar) {
			return value
		}
		valuesSoFar[value] = true
	}
	return null
}

export function getClassesFromClassListValues(value: string): string[] {
	const repaired = jsonrepair(value)
	const array = JSON.parse(repaired)
	if (!Array.isArray(array)) return []

	let classesOnAttribute: string[] = []
	for (const item of array) {
		if (typeof item === "string") {
			classesOnAttribute = [...classesOnAttribute, ...item.split(GLOBALS.EMPTY_CHAR)]
		} else if (typeof item === "object" && item !== null) {
			const firstKey = Object.keys(item)[0]
			if (!firstKey) continue
			classesOnAttribute = [...classesOnAttribute, ...firstKey.split(GLOBALS.EMPTY_CHAR)]
		}
	}
	return classesOnAttribute
}

export function generateUnionTypeFromStringifiedArray(rawValue: string, filePath: string): string {
	try {
		const jsonValue = JSON.parse(rawValue)
		if (typeof jsonValue !== "object" || jsonValue === null || !Array.isArray(jsonValue)) return "never"
		const result = jsonValue.filter((v) => typeof v === "string").map((val) => `"${val}"`)
		return result.join(GLOBALS.PIPE_CHAR)
	} catch (e) {
		throw new HAQError(
			{
				message: "JSON parsing failed.",
				description: rawValue,
				sourceFiles: [filePath]
			},
			{ cause: e }
		)
	}
}

export function getArrayFromStringifiedArray(rawValue: string, filePath: string): string[] {
	try {
		const jsonValue = JSON.parse(rawValue) as string[]
		if (typeof jsonValue !== "object" || jsonValue === null || !Array.isArray(jsonValue)) return []
		return jsonValue
	} catch (e) {
		throw new HAQError(
			{
				message: "JSON parsing failed.",
				description: rawValue,
				sourceFiles: [filePath]
			},
			{ cause: e }
		)
	}
}

export function generateUnionFromArray(array: string[]): string {
	return array.map((val) => `"${val}"`).join(GLOBALS.PIPE_CHAR)
}

export function generateUnionTypeFromSpaceSeparatedList(classes: string): string {
	return classes
		.split(GLOBALS.EMPTY_CHAR)
		.map((val) => `"${val}"`)
		.join(GLOBALS.PIPE_CHAR)
}

export function generateArrayFromSpaceSeparatedList(value: string): string[] {
	return value.split(GLOBALS.EMPTY_CHAR)
}

export function arraysAreEqual(arr1: string[], arr2: string[]): boolean {
	// Check if both arguments are indeed arrays
	if (!(Array.isArray(arr1) && Array.isArray(arr2))) {
		return false
	}

	// Check if lengths are different
	if (arr1.length !== arr2.length) {
		return false
	}

	// Iterate and compare elements
	for (let i = 0; i < arr1.length; i++) {
		// For primitive values, direct comparison is sufficient
		if (arr1[i] !== arr2[i]) {
			return false // This line is for simple element comparison
		}
	}

	return true
}

export function pushToArrayInMap(map: Map<string, string[]>, key: string, element: string): void {
	if (!map.has(key)) {
		map.set(key, [])
	}
	const record = map.get(key)

	if (!record) return

	record.push(element)
	map.set(key, [...record])
}

export function cleanUpObjectValues(value: string): string {
	let sanitizedValue = value
	const objectValueRegex = /{\s*(?:"[^"]*"|'[^']*'|\w+)\s*:\s*([^}]+)}/g
	const matches = value.matchAll(objectValueRegex)
	for (const match of matches) {
		if (!match[1]) continue
		sanitizedValue = sanitizedValue.replace(match[1], "true")
	}
	return sanitizedValue
}
