//#region -------------------------------------------------- Type Imports

import type { TypedOmit } from "@haq/utils/types"
import type {
	AstroComponentsMap,
	CSSMarkupMap,
	JSON_AstroComponent,
	JSON_CSSMarkup,
	JSON_Lists
} from "../cli/_shared/types.js"
import type { ConfigSchema, CustomElementsMap, JSON_CustomElement } from "../cli/_shared/validation.js"

//#endregion ----------------------------------------------- Type Imports

//#region -------------------------------------------------- Module Imports

import path from "node:path"
import { createAstroComponentsMap, createCssMarkupMap, createCustomElementsMap } from "../cli/_shared/astro.js"
import { loadJsonFile } from "../cli/_shared/fs.js"
import { GLOBALS } from "../globals.js"

//#endregion ----------------------------------------------- Module Imports

/*******************************************************************************
 *
 * Function that gets the poject data.
 *
 * @param currentDir The full path of the current directory where the process is running.
 *
 * @returns Object containing the data to pass in to `getGeneratedData`.
 *
 ******************************************************************************/

export function getProjectData(currentDir: string): RT_getProjectData {
	const { outDir, projectDir, globalCssDir } = loadConfig(currentDir)

	const genOutputDir = `${outDir}/${GLOBALS.GENERATED_TYPES_FOLDER}`

	return {
		projectDir,
		outDir,
		globalCssDir,
		nativeElementsContent: loadNativeElementsJson(genOutputDir)
	}
}

type RT_getProjectData = {
	projectDir: string
	outDir: string
	globalCssDir: string
	nativeElementsContent: JSON_CustomElement[]
}

export function loadNativeElementsJson(outDir: string): JSON_CustomElement[] {
	return loadJsonFile(`${outDir}/${GLOBALS.NATIVE_ELEMENTS_JSON_FILE_NAME}`) as JSON_CustomElement[]
}

function loadConfig(currentDir: string): TypedOmit<RT_getProjectData, "nativeElementsContent"> {
	const configContent = loadJsonFile(`${currentDir}/${GLOBALS.HAQ_CONFIG_JSON_FILE_NAME}`) as ConfigSchema

	return {
		projectDir: path.join(currentDir, configContent.projectDir),
		outDir: path.join(currentDir, configContent.outDir),
		globalCssDir: path.join(currentDir, configContent.globalCssDir)
	}
}

/*******************************************************************************
 *
 * Function that gets all the data generated by the `compile` CLI commmand.
 *
 * @param Object returned from `getProjectData()`.
 *
 * @returns Object containing all the data to pass in to tooling (completions/diagnostics).
 *
 ******************************************************************************/

export function getGeneratedData({
	outDir,
	nativeElementsContent
}: Pick<RT_getProjectData, "nativeElementsContent" | "outDir">): RT_getGeneratedData {
	const { customElementsContent, astroComponentsContent, listContent, cssMarkupJsonContent } =
		_loadGeneratedJsonContent()

	return {
		customElementsMap: createCustomElementsMap(customElementsContent, nativeElementsContent),
		astroComponentsMap: createAstroComponentsMap(astroComponentsContent),
		cssMarkupMap: createCssMarkupMap(cssMarkupJsonContent),
		listContent
	}

	//* ---------- Helpers -----------------------------------------------

	type RT__loadJSONContent = {
		listContent: JSON_Lists
		astroComponentsContent: JSON_AstroComponent[]
		customElementsContent: JSON_CustomElement[]
		cssMarkupJsonContent: JSON_CSSMarkup[]
	}
	function _loadGeneratedJsonContent(): RT__loadJSONContent {
		const genOutputDir = `${outDir}/${GLOBALS.GENERATED_TYPES_FOLDER}`

		return {
			listContent: loadJsonFile(`${genOutputDir}/${GLOBALS.GEN_LISTS_JSON_FILE_NAME}`) as JSON_Lists,
			astroComponentsContent: loadJsonFile(
				`${genOutputDir}/${GLOBALS.GEN_ASTRO_COMPONENTS_JSON_FILE_NAME}`
			) as JSON_AstroComponent[],
			customElementsContent: loadJsonFile(
				`${genOutputDir}/${GLOBALS.GEN_CUSTOM_ELEMENTS_JSON_FILE_NAME}`
			) as JSON_CustomElement[],

			cssMarkupJsonContent: loadJsonFile(`${genOutputDir}/${GLOBALS.GEN_CSS_JSON_FILE_NAME}`) as JSON_CSSMarkup[]
		}
	}
}

type RT_getGeneratedData = {
	customElementsMap: CustomElementsMap
	astroComponentsMap: AstroComponentsMap
	cssMarkupMap: CSSMarkupMap
	listContent: JSON_Lists
}
